// Sample agent-partner registrations.
//
// Invented, like everything in seed.ts. Shaped to show the states a manager
// actually has to act on: people who registered and were never called, people
// verified but unable to be paid, and a referral chain.

import type { AgentPartner } from './types'

const DAY = 86_400_000

function daysAgo(n: number, hour = 11): string {
  const d = new Date(Date.now() - n * DAY)
  d.setHours(hour, (n * 11) % 60, 0, 0)
  return d.toISOString()
}

export const PARTNERS: AgentPartner[] = [
  {
    id: 'p-1',
    code: 'AGT-1042',
    fullName: 'Adewale Ogunleye',
    whatsapp: '0803 555 2001',
    email: 'adewale.ogunleye@example.com',
    experience: 'THREE_PLUS',
    agencyName: 'Ogunleye & Sons Realty',
    operatingState: 'Lagos',
    status: 'ACTIVE',
    referredByCode: null,
    ownerId: 'staff-b',
    hasPhoto: true,
    hasBank: true,
    hasNin: true,
    hasTaxId: true,
    registeredAt: daysAgo(34),
    lastContactAt: daysAgo(2),
    notes: 'Brought two Lekki listings in his first month. Reliable.',
  },
  {
    id: 'p-2',
    code: 'AGT-1058',
    fullName: 'Chiamaka Obi',
    whatsapp: '0805 555 2002',
    email: 'chiamaka.obi@example.com',
    experience: 'ONE_TO_THREE',
    agencyName: null,
    operatingState: 'Lagos',
    status: 'VERIFIED',
    referredByCode: 'AGT-1042',
    ownerId: 'staff-e-ngozi',
    hasPhoto: true,
    hasBank: true,
    hasNin: true,
    hasTaxId: false,
    registeredAt: daysAgo(21),
    lastContactAt: daysAgo(6),
    notes: 'Verified. Waiting on her LIRS Payer ID before she can be paid.',
  },
  {
    id: 'p-3',
    code: 'AGT-1071',
    fullName: 'Ibrahim Suleiman',
    whatsapp: '0701 555 2003',
    email: 'ibrahim.suleiman@example.com',
    experience: 'NEW',
    agencyName: null,
    operatingState: 'FCT - Abuja',
    status: 'NEW',
    referredByCode: 'AGT-1042',
    ownerId: null,
    hasPhoto: false,
    hasBank: false,
    hasNin: false,
    hasTaxId: false,
    registeredAt: daysAgo(9),
    lastContactAt: null,
    notes: '',
  },
  {
    id: 'p-4',
    code: 'AGT-1080',
    fullName: 'Folake Adeyinka',
    whatsapp: '0802 555 2004',
    email: 'folake.adeyinka@example.com',
    experience: 'THREE_PLUS',
    agencyName: 'Bright Homes Ltd',
    operatingState: 'Ogun',
    status: 'CONTACTED',
    referredByCode: null,
    ownerId: 'staff-b',
    hasPhoto: true,
    hasBank: false,
    hasNin: true,
    hasTaxId: true,
    registeredAt: daysAgo(7),
    lastContactAt: daysAgo(3),
    notes: 'Runs a small agency in Abeokuta. Wants to know the split.',
  },
  {
    id: 'p-5',
    code: 'AGT-1093',
    fullName: 'Emeka Nwankwo',
    whatsapp: '0806 555 2005',
    email: 'emeka.nwankwo@example.com',
    experience: 'ONE_TO_THREE',
    agencyName: null,
    operatingState: 'Lagos',
    status: 'NEW',
    referredByCode: null,
    ownerId: null,
    hasPhoto: false,
    hasBank: false,
    hasNin: false,
    hasTaxId: false,
    registeredAt: daysAgo(5),
    lastContactAt: null,
    notes: '',
  },
  {
    id: 'p-6',
    code: 'AGT-1101',
    fullName: 'Zainab Bello',
    whatsapp: '0809 555 2006',
    email: 'zainab.bello@example.com',
    experience: 'NEW',
    agencyName: null,
    operatingState: 'Osun',
    status: 'CONTACTED',
    referredByCode: null,
    ownerId: 'staff-sodiq2',
    hasPhoto: true,
    hasBank: true,
    hasNin: false,
    hasTaxId: false,
    registeredAt: daysAgo(4),
    lastContactAt: daysAgo(1),
    notes: 'Osogbo. First Osun partner — worth getting right.',
  },
  {
    id: 'p-7',
    code: 'AGT-1108',
    fullName: 'Tunde Balogun',
    whatsapp: '0803 555 2007',
    email: 'tunde.balogun@example.com',
    experience: 'THREE_PLUS',
    agencyName: 'Balogun Property Partners',
    operatingState: 'Lagos',
    status: 'ACTIVE',
    referredByCode: 'AGT-1042',
    ownerId: 'staff-b',
    hasPhoto: true,
    hasBank: true,
    hasNin: true,
    hasTaxId: true,
    registeredAt: daysAgo(28),
    lastContactAt: daysAgo(4),
    notes: 'Closed one rental already.',
  },
  {
    id: 'p-8',
    code: 'AGT-1115',
    fullName: 'Grace Etim',
    whatsapp: '0805 555 2008',
    email: 'grace.etim@example.com',
    experience: null,
    agencyName: null,
    operatingState: null,
    status: 'NEW',
    referredByCode: null,
    ownerId: null,
    hasPhoto: false,
    hasBank: false,
    hasNin: false,
    hasTaxId: false,
    registeredAt: daysAgo(2),
    lastContactAt: null,
    notes: '',
  },
  {
    id: 'p-9',
    code: 'AGT-1118',
    fullName: 'Samuel Okonkwo',
    whatsapp: '0708 555 2009',
    email: 'samuel.okonkwo@example.com',
    experience: 'ONE_TO_THREE',
    agencyName: 'Unverifiable Estates',
    operatingState: 'Lagos',
    status: 'REJECTED',
    referredByCode: null,
    ownerId: 'staff-e-ngozi',
    hasPhoto: true,
    hasBank: false,
    hasNin: false,
    hasTaxId: false,
    registeredAt: daysAgo(16),
    lastContactAt: daysAgo(12),
    notes: 'Agency name does not exist at CAC. Kept on file as a decline.',
  },
  {
    id: 'p-10',
    code: 'AGT-1120',
    fullName: 'Halima Yusuf',
    whatsapp: '0802 555 2010',
    email: 'halima.yusuf@example.com',
    experience: 'NEW',
    agencyName: null,
    operatingState: 'Kano',
    status: 'DORMANT',
    referredByCode: null,
    ownerId: 'staff-e-ngozi',
    hasPhoto: false,
    hasBank: false,
    hasNin: false,
    hasTaxId: false,
    registeredAt: daysAgo(40),
    lastContactAt: daysAgo(30),
    notes: 'Registered, never replied to three follow-ups.',
  },
  {
    id: 'p-11',
    code: 'AGT-1124',
    fullName: 'Kelechi Anyaoku',
    whatsapp: '0806 555 2011',
    email: 'kelechi.anyaoku@example.com',
    experience: 'THREE_PLUS',
    agencyName: null,
    operatingState: 'Rivers',
    status: 'NEW',
    referredByCode: 'AGT-1108',
    ownerId: null,
    hasPhoto: true,
    hasBank: true,
    hasNin: true,
    hasTaxId: true,
    registeredAt: daysAgo(1),
    lastContactAt: null,
    notes: '',
  },
  {
    id: 'p-12',
    code: 'AGT-1127',
    fullName: 'Aisha Lawal',
    whatsapp: '0809 555 2012',
    email: 'aisha.lawal@example.com',
    experience: 'ONE_TO_THREE',
    agencyName: null,
    operatingState: 'Lagos',
    status: 'VERIFIED',
    referredByCode: null,
    ownerId: 'staff-b',
    hasPhoto: true,
    hasBank: true,
    hasNin: true,
    hasTaxId: true,
    registeredAt: daysAgo(12),
    lastContactAt: daysAgo(5),
    notes: 'Ready to list. Needs the onboarding call.',
  },
]
