// Seed data for the staff portal.
//
// Every figure here is INVENTED. It exists so the screens can be judged with
// realistic density before the API is wired up. Nothing in this file should
// ever be quoted as a real PropertyLoop number.
//
// Dates are generated relative to load time so the portal never looks stale
// during a demo.

import type {
  ContentPiece,
  Deal,
  Lead,
  OpsItem,
  Property,
  PropertyDoc,
  Shoot,
  Staff,
  Target,
  Thread,
} from './types'
import { DocumentType } from './types'
import { ROLE_PERMISSIONS } from './permissions'

const DAY = 86_400_000

function daysAgo(n: number, hour = 10): string {
  const d = new Date(Date.now() - n * DAY)
  d.setHours(hour, (n * 7) % 60, 0, 0)
  return d.toISOString()
}

function daysAhead(n: number, hour = 10): string {
  const d = new Date(Date.now() + n * DAY)
  d.setHours(hour, (n * 13) % 60, 0, 0)
  return d.toISOString()
}

function hoursAgo(n: number): string {
  return new Date(Date.now() - n * 3_600_000).toISOString()
}

/* ─── Staff ──────────────────────────────────────────────────────────── */

// Names are filled in where the org document assigns one. The rest carry
// their staff letter until a person is named — better an obvious gap than a
// placeholder that reads like a real employee.
export const STAFF: Staff[] = [
  {
    id: 'staff-a',
    letter: 'A',
    name: null,
    role: 'MD_CEO',
    permissions: ROLE_PERMISSIONS['MD_CEO'],
    chapter: 'LAGOS',
    email: null,
    reportsTo: null,
    active: true,
  },
  {
    id: 'staff-b',
    letter: 'B',
    name: null,
    role: 'GM',
    permissions: ROLE_PERMISSIONS['GM'],
    chapter: 'LAGOS',
    email: null,
    reportsTo: 'staff-a',
    active: true,
  },
  {
    id: 'staff-c-ola',
    letter: 'C',
    name: 'Ola',
    role: 'PROPERTY_LISTING',
    permissions: ROLE_PERMISSIONS['PROPERTY_LISTING'],
    chapter: 'LAGOS',
    email: null,
    reportsTo: 'staff-b',
    active: true,
  },
  {
    id: 'staff-c-sodiq1',
    letter: 'C',
    name: 'Sodiq (1st)',
    role: 'PROPERTY_LISTING',
    permissions: ROLE_PERMISSIONS['PROPERTY_LISTING'],
    chapter: 'LAGOS',
    secondaryChapter: 'OSUN',
    email: null,
    reportsTo: 'staff-b',
    active: true,
  },
  {
    id: 'staff-d',
    letter: 'D',
    name: null,
    role: 'MARKETING',
    permissions: ROLE_PERMISSIONS['MARKETING'],
    chapter: 'LAGOS',
    email: null,
    reportsTo: 'staff-b',
    active: true,
  },
  {
    id: 'staff-e-ngozi',
    letter: 'E',
    name: 'Ngozi',
    role: 'OPERATIONS',
    permissions: ROLE_PERMISSIONS['OPERATIONS'],
    chapter: 'LAGOS',
    email: null,
    reportsTo: 'staff-b',
    active: true,
  },
  {
    id: 'staff-f',
    letter: 'F',
    name: null,
    role: 'AMBASSADOR',
    permissions: ROLE_PERMISSIONS['AMBASSADOR'],
    chapter: 'LAGOS',
    email: null,
    reportsTo: 'staff-b',
    active: true,
  },
  {
    id: 'staff-g',
    letter: 'G',
    name: null,
    role: 'SECRETARY',
    permissions: ROLE_PERMISSIONS['SECRETARY'],
    chapter: 'LAGOS',
    email: null,
    reportsTo: 'staff-b',
    active: true,
  },
  {
    id: 'staff-sodiq2',
    letter: 'C',
    name: 'Sodiq (2nd)',
    role: 'PROPERTY_LISTING',
    permissions: ROLE_PERMISSIONS['PROPERTY_LISTING'],
    chapter: 'OSUN',
    email: null,
    reportsTo: 'staff-b',
    active: true,
  },
]

/* ─── Deals ──────────────────────────────────────────────────────────── */

export const DEALS: Deal[] = [
  {
    id: 'deal-1',
    company: 'Cedarwood Developments',
    contactName: 'Tunde Bakare',
    contactPhone: '0803 555 0141',
    kind: 'DEVELOPER',
    stage: 'MANDATE_SIGNED',
    mandate: 'EXCLUSIVE',
    valueNaira: 14_500_000,
    expectedUnits: 24,
    ownerId: 'staff-a',
    chapter: 'LAGOS',
    createdAt: daysAgo(52),
    lastActivityAt: daysAgo(3),
    nextActionAt: daysAhead(2),
    nextAction: 'Collect remaining unit pricing sheet',
    notes:
      'Exclusive on Phase 2 only. Phase 1 already with another agency until March.',
  },
  {
    id: 'deal-2',
    company: 'Alaro Court Estate',
    contactName: 'Ifeoma Nwosu',
    contactPhone: '0805 555 0192',
    kind: 'DEVELOPER',
    stage: 'INVENTORY_RECEIVED',
    mandate: 'PRIMARY',
    valueNaira: 9_200_000,
    expectedUnits: 16,
    ownerId: 'staff-b',
    chapter: 'LAGOS',
    createdAt: daysAgo(38),
    lastActivityAt: daysAgo(1),
    nextActionAt: daysAhead(1),
    nextAction: 'Push for exclusive before competitor meeting Thursday',
    notes: 'Inventory received for 16 units. Wants co-branded launch campaign.',
  },
  {
    id: 'deal-3',
    company: 'Sterling Heights Ltd',
    contactName: 'Emeka Obi',
    contactPhone: '0701 555 0233',
    kind: 'DEVELOPER',
    stage: 'MEETING',
    mandate: 'NONE',
    valueNaira: 7_800_000,
    expectedUnits: 12,
    ownerId: 'staff-b',
    chapter: 'LAGOS',
    createdAt: daysAgo(21),
    lastActivityAt: daysAgo(6),
    nextActionAt: daysAgo(1),
    nextAction: 'Send follow-up deck after site visit',
    notes: 'Site visit went well. Decision maker is the MD, not Emeka.',
  },
  {
    id: 'deal-4',
    company: 'Zenith Bank — Lekki Branch',
    contactName: 'Adaeze Okafor',
    contactPhone: '0802 555 0177',
    kind: 'ADVERTISER',
    stage: 'PRESENTATION_SENT',
    mandate: 'NONE',
    valueNaira: 3_500_000,
    expectedUnits: 0,
    ownerId: 'staff-b',
    chapter: 'LAGOS',
    createdAt: daysAgo(14),
    lastActivityAt: daysAgo(4),
    nextActionAt: daysAhead(3),
    nextAction: 'Chase decision on Q4 banner package',
    notes: 'Interested in homepage placement + WhatsApp Channel mentions.',
  },
  {
    id: 'deal-5',
    company: 'Harmony Facility Services',
    contactName: 'Bola Adeyemi',
    contactPhone: '0806 555 0288',
    kind: 'FACILITY_MANAGEMENT',
    stage: 'CONTACTED',
    mandate: 'NONE',
    valueNaira: 5_000_000,
    expectedUnits: 0,
    ownerId: 'staff-b',
    chapter: 'LAGOS',
    createdAt: daysAgo(9),
    lastActivityAt: daysAgo(9),
    nextActionAt: daysAgo(4),
    nextAction: 'No follow-up logged since first call',
    notes: 'Manages 3 estates in Ajah. Wants pricing for 200+ units.',
  },
  {
    id: 'deal-6',
    company: 'Greenfield Homes',
    contactName: 'Yusuf Lawal',
    contactPhone: '0803 555 0311',
    kind: 'DEVELOPER',
    stage: 'PUBLISHED',
    mandate: 'EXCLUSIVE',
    valueNaira: 18_000_000,
    expectedUnits: 30,
    ownerId: 'staff-a',
    chapter: 'LAGOS',
    createdAt: daysAgo(88),
    lastActivityAt: daysAgo(7),
    nextActionAt: daysAhead(9),
    nextAction: 'Monthly performance review with developer',
    notes: '30 units live. 6 sold through PropertyLoop so far.',
  },
  {
    id: 'deal-7',
    company: 'Osun Grove Estate',
    contactName: 'Rasheed Adebayo',
    contactPhone: '0705 555 0344',
    kind: 'DEVELOPER',
    stage: 'INVENTORY_RECEIVED',
    mandate: 'PRIMARY',
    valueNaira: 4_200_000,
    expectedUnits: 14,
    ownerId: 'staff-sodiq2',
    chapter: 'OSUN',
    createdAt: daysAgo(30),
    lastActivityAt: daysAgo(2),
    nextActionAt: daysAhead(4),
    nextAction: 'Photograph remaining 6 units',
    notes: 'First serious Osun inventory. Pricing well below Lagos comparables.',
  },
  {
    id: 'deal-8',
    company: 'Ile-Ife Property Partners',
    contactName: 'Kunle Ogundipe',
    contactPhone: '0708 555 0399',
    kind: 'REALTOR',
    stage: 'MEETING',
    mandate: 'NONE',
    valueNaira: 1_800_000,
    expectedUnits: 8,
    ownerId: 'staff-sodiq2',
    chapter: 'OSUN',
    createdAt: daysAgo(17),
    lastActivityAt: daysAgo(5),
    nextActionAt: daysAhead(2),
    nextAction: 'Agree commission split',
    notes: 'Small agency, 4 agents. Wants to list through us in Osun.',
  },
  {
    id: 'deal-9',
    company: 'Marble & Stone Interiors',
    contactName: 'Chioma Eze',
    contactPhone: '0809 555 0422',
    kind: 'BUILDING_FINISHING',
    stage: 'IDENTIFIED',
    mandate: 'NONE',
    valueNaira: 2_400_000,
    expectedUnits: 0,
    ownerId: 'staff-c-ola',
    chapter: 'LAGOS',
    createdAt: daysAgo(5),
    lastActivityAt: daysAgo(5),
    nextActionAt: daysAhead(1),
    nextAction: 'First call',
    notes: 'Referred by Greenfield. Does finishing for 3 estates.',
  },
  {
    id: 'deal-10',
    company: 'Pinnacle Properties',
    contactName: 'Segun Alabi',
    contactPhone: '0802 555 0455',
    kind: 'DEVELOPER',
    stage: 'LOST',
    mandate: 'NONE',
    valueNaira: 11_000_000,
    expectedUnits: 20,
    ownerId: 'staff-b',
    chapter: 'LAGOS',
    createdAt: daysAgo(64),
    lastActivityAt: daysAgo(19),
    nextActionAt: null,
    nextAction: null,
    notes: 'Went with an incumbent agency. Revisit when Phase 3 launches.',
  },
  {
    id: 'deal-11',
    company: 'MTN Nigeria — Brand Team',
    contactName: 'Halima Sani',
    contactPhone: '0803 555 0488',
    kind: 'ADVERTISER',
    stage: 'IDENTIFIED',
    mandate: 'NONE',
    valueNaira: 6_000_000,
    expectedUnits: 0,
    ownerId: 'staff-a',
    chapter: 'LAGOS',
    createdAt: daysAgo(3),
    lastActivityAt: daysAgo(3),
    nextActionAt: daysAhead(5),
    nextAction: 'Warm intro via Cedarwood contact',
    notes: 'Long shot but high value. Approach through introduction only.',
  },
  {
    id: 'deal-12',
    company: 'Crestview Apartments',
    contactName: 'Ngozi Uche',
    contactPhone: '0806 555 0511',
    kind: 'DEVELOPER',
    stage: 'CONTACTED',
    mandate: 'NONE',
    valueNaira: 8_500_000,
    expectedUnits: 18,
    ownerId: 'staff-c-sodiq1',
    chapter: 'LAGOS',
    createdAt: daysAgo(11),
    lastActivityAt: daysAgo(2),
    nextActionAt: daysAhead(1),
    nextAction: 'Send partnership deck',
    notes: 'Responded positively on WhatsApp. Wants to see our developer pack.',
  },
  {
    id: 'deal-13',
    company: 'Beacon Realty',
    contactName: 'Femi Oladele',
    contactPhone: '0807 555 0544',
    kind: 'REALTOR',
    stage: 'MANDATE_SIGNED',
    mandate: 'OPEN',
    valueNaira: 2_100_000,
    expectedUnits: 9,
    ownerId: 'staff-b',
    chapter: 'LAGOS',
    createdAt: daysAgo(26),
    lastActivityAt: daysAgo(4),
    nextActionAt: daysAhead(6),
    nextAction: 'Onboard their 3 agents onto the platform',
    notes: 'Open mandate. Their agents need PropertyLoop accounts.',
  },
  {
    id: 'deal-14',
    company: 'Lagoon View Facility Mgmt',
    contactName: 'Tolu Ayinde',
    contactPhone: '0805 555 0577',
    kind: 'FACILITY_MANAGEMENT',
    stage: 'PRESENTATION_SENT',
    mandate: 'NONE',
    valueNaira: 4_800_000,
    expectedUnits: 0,
    ownerId: 'staff-e-ngozi',
    chapter: 'LAGOS',
    createdAt: daysAgo(12),
    lastActivityAt: daysAgo(3),
    nextActionAt: daysAhead(4),
    nextAction: 'Follow up on proposal',
    notes: 'Proposal sent for 2 estates in Ikoyi.',
  },
]

/* ─── Properties ─────────────────────────────────────────────────────── */

function docs(
  cofo: boolean,
  survey: boolean,
  permit: boolean,
  receipt: boolean,
  verifiedCount: number,
): PropertyDoc[] {
  const present = [cofo, survey, permit, receipt]
  const types = [
    DocumentType.C_OF_O,
    DocumentType.SURVEY_PLAN,
    DocumentType.BUILDING_PERMIT,
    DocumentType.RECEIPT,
  ]
  let remaining = verifiedCount
  return types.map((type, i) => {
    const isPresent = present[i]
    const verified = isPresent && remaining > 0
    if (verified) remaining -= 1
    return { type, present: isPresent, verified }
  })
}

export const PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    title: '3-Bed Terrace, Cedarwood Phase 2',
    location: 'Lekki Phase 1, Lagos',
    chapter: 'LAGOS',
    type: 'SALE',
    priceNaira: 145_000_000,
    developer: 'Cedarwood Developments',
    dealId: 'deal-1',
    status: 'ACTIVE',
    verified: true,
    photoCount: 18,
    hasVideo: true,
    documents: docs(true, true, true, true, 4),
    sourcedById: 'staff-c-ola',
    submittedAt: daysAgo(24),
    publishedAt: daysAgo(19),
    units: 6,
    unitsSold: 2,
  },
  {
    id: 'prop-2',
    title: '4-Bed Detached, Greenfield Estate',
    location: 'Ikate, Lagos',
    chapter: 'LAGOS',
    type: 'SALE',
    priceNaira: 210_000_000,
    developer: 'Greenfield Homes',
    dealId: 'deal-6',
    status: 'ACTIVE',
    verified: true,
    photoCount: 24,
    hasVideo: true,
    documents: docs(true, true, true, true, 4),
    sourcedById: 'staff-c-ola',
    submittedAt: daysAgo(40),
    publishedAt: daysAgo(35),
    units: 8,
    unitsSold: 3,
  },
  {
    id: 'prop-3',
    title: '2-Bed Apartment, Alaro Court',
    location: 'Ajah, Lagos',
    chapter: 'LAGOS',
    type: 'SALE',
    priceNaira: 78_000_000,
    developer: 'Alaro Court Estate',
    dealId: 'deal-2',
    status: 'PENDING_REVIEW',
    verified: false,
    photoCount: 6,
    hasVideo: false,
    documents: docs(true, true, false, false, 1),
    sourcedById: 'staff-c-sodiq1',
    submittedAt: daysAgo(6),
    publishedAt: null,
    units: 10,
    unitsSold: 0,
  },
  {
    id: 'prop-4',
    title: '5-Bed Duplex, Banana Island',
    location: 'Ikoyi, Lagos',
    chapter: 'LAGOS',
    type: 'SALE',
    priceNaira: 950_000_000,
    developer: null,
    dealId: null,
    status: 'ACTIVE',
    verified: true,
    photoCount: 31,
    hasVideo: true,
    documents: docs(true, true, true, true, 4),
    sourcedById: 'staff-b',
    submittedAt: daysAgo(55),
    publishedAt: daysAgo(50),
    units: 1,
    unitsSold: 0,
  },
  {
    id: 'prop-5',
    title: '3-Bed Flat, Osun Grove',
    location: 'Osogbo, Osun',
    chapter: 'OSUN',
    type: 'SALE',
    priceNaira: 42_000_000,
    developer: 'Osun Grove Estate',
    dealId: 'deal-7',
    status: 'PENDING_REVIEW',
    verified: false,
    photoCount: 11,
    hasVideo: false,
    documents: docs(true, false, false, true, 1),
    sourcedById: 'staff-sodiq2',
    submittedAt: daysAgo(4),
    publishedAt: null,
    units: 6,
    unitsSold: 0,
  },
  {
    id: 'prop-6',
    title: '2-Bed Serviced Apartment',
    location: 'Victoria Island, Lagos',
    chapter: 'LAGOS',
    type: 'RENT',
    priceNaira: 8_500_000,
    developer: null,
    dealId: null,
    status: 'ACTIVE',
    verified: true,
    photoCount: 15,
    hasVideo: false,
    documents: docs(true, true, true, true, 4),
    sourcedById: 'staff-c-ola',
    submittedAt: daysAgo(31),
    publishedAt: daysAgo(28),
    units: 4,
    unitsSold: 1,
  },
  {
    id: 'prop-7',
    title: '1-Bed Shortlet, Lekki Swiss Mall Area',
    location: 'Lekki, Lagos',
    chapter: 'LAGOS',
    type: 'SHORTLET',
    priceNaira: 85_000,
    developer: null,
    dealId: null,
    status: 'ACTIVE',
    verified: true,
    photoCount: 12,
    hasVideo: true,
    documents: docs(true, true, true, true, 4),
    sourcedById: 'staff-e-ngozi',
    submittedAt: daysAgo(22),
    publishedAt: daysAgo(20),
    units: 3,
    unitsSold: 0,
  },
  {
    id: 'prop-8',
    title: '4-Bed Semi-Detached, Crestview',
    location: 'Chevron Drive, Lagos',
    chapter: 'LAGOS',
    type: 'SALE',
    priceNaira: 165_000_000,
    developer: 'Crestview Apartments',
    dealId: 'deal-12',
    status: 'PENDING_REVIEW',
    verified: false,
    photoCount: 3,
    hasVideo: false,
    documents: docs(false, true, false, false, 0),
    sourcedById: 'staff-c-sodiq1',
    submittedAt: daysAgo(2),
    publishedAt: null,
    units: 12,
    unitsSold: 0,
  },
  {
    id: 'prop-9',
    title: '3-Bed Bungalow, Ile-Ife',
    location: 'Ile-Ife, Osun',
    chapter: 'OSUN',
    type: 'SALE',
    priceNaira: 28_000_000,
    developer: null,
    dealId: 'deal-8',
    status: 'PENDING_REVIEW',
    verified: false,
    photoCount: 8,
    hasVideo: false,
    documents: docs(true, true, false, false, 2),
    sourcedById: 'staff-sodiq2',
    submittedAt: daysAgo(8),
    publishedAt: null,
    units: 2,
    unitsSold: 0,
  },
  {
    id: 'prop-10',
    title: '2-Bed Flat, Yaba',
    location: 'Yaba, Lagos',
    chapter: 'LAGOS',
    type: 'RENT',
    priceNaira: 4_200_000,
    developer: null,
    dealId: null,
    status: 'RENTED',
    verified: true,
    photoCount: 14,
    hasVideo: false,
    documents: docs(true, true, true, true, 4),
    sourcedById: 'staff-c-ola',
    submittedAt: daysAgo(70),
    publishedAt: daysAgo(66),
    units: 1,
    unitsSold: 1,
  },
  {
    id: 'prop-11',
    title: '5-Bed Detached, Cedarwood Phase 2',
    location: 'Lekki Phase 1, Lagos',
    chapter: 'LAGOS',
    type: 'SALE',
    priceNaira: 320_000_000,
    developer: 'Cedarwood Developments',
    dealId: 'deal-1',
    status: 'ACTIVE',
    verified: true,
    photoCount: 22,
    hasVideo: true,
    documents: docs(true, true, true, true, 4),
    sourcedById: 'staff-c-ola',
    submittedAt: daysAgo(23),
    publishedAt: daysAgo(18),
    units: 4,
    unitsSold: 1,
  },
  {
    id: 'prop-12',
    title: 'Studio Apartment, Surulere',
    location: 'Surulere, Lagos',
    chapter: 'LAGOS',
    type: 'RENT',
    priceNaira: 2_800_000,
    developer: null,
    dealId: null,
    status: 'PAUSED',
    verified: true,
    photoCount: 9,
    hasVideo: false,
    documents: docs(true, true, true, true, 4),
    sourcedById: 'staff-e-ngozi',
    submittedAt: daysAgo(45),
    publishedAt: daysAgo(41),
    units: 1,
    unitsSold: 0,
  },
  {
    id: 'prop-13',
    title: '4-Bed Terrace, Greenfield Phase 3',
    location: 'Ikate, Lagos',
    chapter: 'LAGOS',
    type: 'SALE',
    priceNaira: 185_000_000,
    developer: 'Greenfield Homes',
    dealId: 'deal-6',
    status: 'SOLD',
    verified: true,
    photoCount: 20,
    hasVideo: true,
    documents: docs(true, true, true, true, 4),
    sourcedById: 'staff-c-ola',
    submittedAt: daysAgo(62),
    publishedAt: daysAgo(58),
    units: 1,
    unitsSold: 1,
  },
  {
    id: 'prop-14',
    title: '3-Bed Apartment, Osun Grove Block B',
    location: 'Osogbo, Osun',
    chapter: 'OSUN',
    type: 'SALE',
    priceNaira: 38_500_000,
    developer: 'Osun Grove Estate',
    dealId: 'deal-7',
    status: 'PENDING_REVIEW',
    verified: false,
    photoCount: 5,
    hasVideo: false,
    documents: docs(true, false, false, false, 0),
    sourcedById: 'staff-sodiq2',
    submittedAt: daysAgo(1),
    publishedAt: null,
    units: 8,
    unitsSold: 0,
  },
  {
    id: 'prop-15',
    title: '2-Bed Shortlet, Ikoyi',
    location: 'Ikoyi, Lagos',
    chapter: 'LAGOS',
    type: 'SHORTLET',
    priceNaira: 140_000,
    developer: null,
    dealId: null,
    status: 'ACTIVE',
    verified: true,
    photoCount: 16,
    hasVideo: true,
    documents: docs(true, true, true, true, 4),
    sourcedById: 'staff-b',
    submittedAt: daysAgo(36),
    publishedAt: daysAgo(33),
    units: 2,
    unitsSold: 0,
  },
  {
    id: 'prop-16',
    title: '6-Bed Mansion, Lekki County',
    location: 'Lekki, Lagos',
    chapter: 'LAGOS',
    type: 'SALE',
    priceNaira: 480_000_000,
    developer: null,
    dealId: null,
    status: 'PENDING_REVIEW',
    verified: false,
    photoCount: 0,
    hasVideo: false,
    documents: docs(false, false, false, false, 0),
    sourcedById: 'staff-c-sodiq1',
    submittedAt: hoursAgo(20),
    publishedAt: null,
    units: 1,
    unitsSold: 0,
  },
  {
    id: 'prop-17',
    title: '3-Bed Flat, Ajah',
    location: 'Ajah, Lagos',
    chapter: 'LAGOS',
    type: 'RENT',
    priceNaira: 3_500_000,
    developer: null,
    dealId: null,
    status: 'ACTIVE',
    verified: true,
    photoCount: 13,
    hasVideo: false,
    documents: docs(true, true, true, true, 4),
    sourcedById: 'staff-c-ola',
    submittedAt: daysAgo(27),
    publishedAt: daysAgo(25),
    units: 2,
    unitsSold: 0,
  },
  {
    id: 'prop-18',
    title: '4-Bed Duplex, Osogbo GRA',
    location: 'Osogbo, Osun',
    chapter: 'OSUN',
    type: 'SALE',
    priceNaira: 55_000_000,
    developer: null,
    dealId: null,
    status: 'ACTIVE',
    verified: true,
    photoCount: 17,
    hasVideo: false,
    documents: docs(true, true, true, true, 4),
    sourcedById: 'staff-sodiq2',
    submittedAt: daysAgo(20),
    publishedAt: daysAgo(15),
    units: 1,
    unitsSold: 0,
  },
]

/* ─── Leads ──────────────────────────────────────────────────────────── */

export const LEADS: Lead[] = [
  {
    id: 'lead-1',
    name: 'Chidi Anyanwu',
    phone: '0803 555 1001',
    source: 'LISTING_PAGE',
    status: 'NEGOTIATING',
    qualified: true,
    propertyId: 'prop-1',
    budgetNaira: 150_000_000,
    ownerId: 'staff-b',
    createdAt: daysAgo(12),
    lastContactAt: daysAgo(1),
    firstResponseMins: 14,
    notes: 'Offered ₦138m. Wants to close before end of quarter.',
  },
  {
    id: 'lead-2',
    name: 'Fatima Bello',
    phone: '0805 555 1002',
    source: 'OTHER',
    status: 'CONTACTED',
    qualified: true,
    propertyId: 'prop-2',
    budgetNaira: 200_000_000,
    ownerId: 'staff-e-ngozi',
    createdAt: daysAgo(5),
    lastContactAt: daysAgo(2),
    firstResponseMins: 22,
    notes: 'Diaspora buyer, currently in London. Video tour requested.',
  },
  {
    id: 'lead-3',
    name: 'Olumide Fashola',
    phone: '0701 555 1003',
    source: 'REFERRAL',
    status: 'VIEWING_SCHEDULED',
    qualified: true,
    propertyId: 'prop-11',
    budgetNaira: 350_000_000,
    ownerId: 'staff-b',
    createdAt: daysAgo(8),
    lastContactAt: daysAgo(1),
    firstResponseMins: 8,
    notes: 'Referred by Greenfield. Viewing Saturday 11am.',
  },
  {
    id: 'lead-4',
    name: 'Grace Okon',
    phone: '0802 555 1004',
    source: 'LISTING_PAGE',
    status: 'NEW',
    qualified: false,
    propertyId: 'prop-6',
    budgetNaira: null,
    ownerId: 'staff-e-ngozi',
    createdAt: hoursAgo(3),
    lastContactAt: null,
    firstResponseMins: null,
    notes: '',
  },
  {
    id: 'lead-5',
    name: 'Ibrahim Yakubu',
    phone: '0806 555 1005',
    source: 'AGENT_PROFILE',
    status: 'NEW',
    qualified: false,
    propertyId: null,
    budgetNaira: null,
    ownerId: 'staff-e-ngozi',
    createdAt: hoursAgo(1),
    lastContactAt: null,
    firstResponseMins: null,
    notes: '',
  },
  {
    id: 'lead-6',
    name: 'Blessing Eze',
    phone: '0809 555 1006',
    source: 'PHONE',
    status: 'CONVERTED',
    qualified: true,
    propertyId: 'prop-13',
    budgetNaira: 185_000_000,
    ownerId: 'staff-b',
    createdAt: daysAgo(45),
    lastContactAt: daysAgo(9),
    firstResponseMins: 5,
    notes: 'Closed. Greenfield Phase 3 terrace.',
  },
  {
    id: 'lead-7',
    name: 'Samuel Adeniyi',
    phone: '0803 555 1007',
    source: 'LISTING_PAGE',
    status: 'LOST',
    qualified: true,
    propertyId: 'prop-4',
    budgetNaira: 700_000_000,
    ownerId: 'staff-b',
    createdAt: daysAgo(33),
    lastContactAt: daysAgo(15),
    firstResponseMins: 41,
    notes: 'Budget short of asking by ₦250m. Went elsewhere.',
  },
  {
    id: 'lead-8',
    name: 'Amaka Nwachukwu',
    phone: '0805 555 1008',
    source: 'EMAIL',
    status: 'CONTACTED',
    qualified: false,
    propertyId: 'prop-17',
    budgetNaira: null,
    ownerId: 'staff-e-ngozi',
    createdAt: daysAgo(3),
    lastContactAt: daysAgo(3),
    firstResponseMins: 55,
    notes: 'Asked about rent. No budget confirmed yet.',
  },
  {
    id: 'lead-9',
    name: 'Tobi Adeleke',
    phone: '0708 555 1009',
    source: 'LISTING_PAGE',
    status: 'VIEWING_SCHEDULED',
    qualified: true,
    propertyId: 'prop-18',
    budgetNaira: 60_000_000,
    ownerId: 'staff-sodiq2',
    createdAt: daysAgo(6),
    lastContactAt: daysAgo(2),
    firstResponseMins: 18,
    notes: 'Osogbo viewing booked for Friday.',
  },
  {
    id: 'lead-10',
    name: 'Kemi Oyelaran',
    phone: '0802 555 1010',
    source: 'REFERRAL',
    status: 'NEGOTIATING',
    qualified: true,
    propertyId: 'prop-2',
    budgetNaira: 195_000_000,
    ownerId: 'staff-b',
    createdAt: daysAgo(18),
    lastContactAt: hoursAgo(30),
    firstResponseMins: 11,
    notes: 'Wants payment plan over 12 months.',
  },
  {
    id: 'lead-11',
    name: 'Daniel Okoro',
    phone: '0806 555 1011',
    source: 'LISTING_PAGE',
    status: 'NEW',
    qualified: false,
    propertyId: 'prop-7',
    budgetNaira: null,
    ownerId: 'staff-e-ngozi',
    createdAt: hoursAgo(7),
    lastContactAt: null,
    firstResponseMins: null,
    notes: 'Shortlet enquiry for December.',
  },
  {
    id: 'lead-12',
    name: 'Halima Abubakar',
    phone: '0809 555 1012',
    source: 'OTHER',
    status: 'CONTACTED',
    qualified: true,
    propertyId: 'prop-15',
    budgetNaira: 1_500_000,
    ownerId: 'staff-e-ngozi',
    createdAt: daysAgo(4),
    lastContactAt: daysAgo(1),
    firstResponseMins: 26,
    notes: 'Corporate shortlet booking, 2 weeks in November.',
  },
  {
    id: 'lead-13',
    name: 'Peter Uzo',
    phone: '0803 555 1013',
    source: 'AGENT_PROFILE',
    status: 'CONTACTED',
    qualified: false,
    propertyId: null,
    budgetNaira: null,
    ownerId: 'staff-d',
    createdAt: daysAgo(2),
    lastContactAt: daysAgo(2),
    firstResponseMins: 33,
    notes: 'Came from LinkedIn campaign. Browsing only.',
  },
  {
    id: 'lead-14',
    name: 'Sarah Johnson',
    phone: '0805 555 1014',
    source: 'LISTING_PAGE',
    status: 'NEW',
    qualified: false,
    propertyId: 'prop-3',
    budgetNaira: null,
    ownerId: 'staff-e-ngozi',
    createdAt: hoursAgo(14),
    lastContactAt: null,
    firstResponseMins: null,
    notes: '',
  },
  {
    id: 'lead-15',
    name: 'Musa Danjuma',
    phone: '0701 555 1015',
    source: 'REFERRAL',
    status: 'NEGOTIATING',
    qualified: true,
    propertyId: 'prop-4',
    budgetNaira: 900_000_000,
    ownerId: 'staff-a',
    createdAt: daysAgo(22),
    lastContactAt: daysAgo(3),
    firstResponseMins: 4,
    notes: 'Serious. CEO handling personally. Second viewing done.',
  },
  {
    id: 'lead-16',
    name: 'Ruth Adamu',
    phone: '0806 555 1016',
    source: 'EMAIL',
    status: 'CONTACTED',
    qualified: false,
    propertyId: 'prop-12',
    budgetNaira: null,
    ownerId: 'staff-e-ngozi',
    createdAt: daysAgo(7),
    lastContactAt: daysAgo(6),
    firstResponseMins: 72,
    notes: 'Slow response — was over the SLA.',
  },
  {
    id: 'lead-17',
    name: 'Victor Ekpo',
    phone: '0802 555 1017',
    source: 'LISTING_PAGE',
    status: 'CONVERTED',
    qualified: true,
    propertyId: 'prop-10',
    budgetNaira: 4_200_000,
    ownerId: 'staff-c-ola',
    createdAt: daysAgo(40),
    lastContactAt: daysAgo(12),
    firstResponseMins: 16,
    notes: 'Yaba flat let. Tenant moved in.',
  },
  {
    id: 'lead-18',
    name: 'Aisha Mohammed',
    phone: '0809 555 1018',
    source: 'LISTING_PAGE',
    status: 'NEW',
    qualified: false,
    propertyId: 'prop-5',
    budgetNaira: null,
    ownerId: 'staff-sodiq2',
    createdAt: hoursAgo(5),
    lastContactAt: null,
    firstResponseMins: null,
    notes: '',
  },
  {
    id: 'lead-19',
    name: 'Emmanuel Bassey',
    phone: '0803 555 1019',
    source: 'PHONE',
    status: 'VIEWING_SCHEDULED',
    qualified: true,
    propertyId: 'prop-1',
    budgetNaira: 140_000_000,
    ownerId: 'staff-b',
    createdAt: daysAgo(9),
    lastContactAt: daysAgo(2),
    firstResponseMins: 7,
    notes: 'Viewing Sunday with spouse.',
  },
  {
    id: 'lead-20',
    name: 'Funke Adebola',
    phone: '0805 555 1020',
    source: 'OTHER',
    status: 'CONTACTED',
    qualified: true,
    propertyId: 'prop-6',
    budgetNaira: 9_000_000,
    ownerId: 'staff-e-ngozi',
    createdAt: daysAgo(6),
    lastContactAt: daysAgo(4),
    firstResponseMins: 19,
    notes: 'VI serviced apartment. Company lease.',
  },
  {
    id: 'lead-21',
    name: 'Nnamdi Chukwu',
    phone: '0708 555 1021',
    source: 'AGENT_PROFILE',
    status: 'LOST',
    qualified: false,
    propertyId: null,
    budgetNaira: null,
    ownerId: 'staff-d',
    createdAt: daysAgo(28),
    lastContactAt: daysAgo(21),
    firstResponseMins: 90,
    notes: 'Never responded after first message.',
  },
  {
    id: 'lead-22',
    name: 'Zainab Lawal',
    phone: '0802 555 1022',
    source: 'REFERRAL',
    status: 'NEW',
    qualified: false,
    propertyId: 'prop-11',
    budgetNaira: null,
    ownerId: 'staff-b',
    createdAt: hoursAgo(2),
    lastContactAt: null,
    firstResponseMins: null,
    notes: '',
  },
]

/* ─── Shoots ─────────────────────────────────────────────────────────── */

export const SHOOTS: Shoot[] = [
  {
    id: 'shoot-1',
    propertyId: 'prop-1',
    title: 'Cedarwood Phase 2 — 3-bed terrace walkthrough',
    location: 'Lekki Phase 1, Lagos',
    stage: 'PUBLISHED',
    scheduledFor: daysAgo(14),
    prepCompleteAt: daysAgo(16),
    presenterId: 'staff-f',
    secretaryId: 'staff-g',
    reshoot: false,
    engagementRate: 6.2,
    publishedAt: daysAgo(11),
  },
  {
    id: 'shoot-2',
    propertyId: 'prop-2',
    title: 'Greenfield 4-bed detached tour',
    location: 'Ikate, Lagos',
    stage: 'PUBLISHED',
    scheduledFor: daysAgo(21),
    prepCompleteAt: daysAgo(23),
    presenterId: 'staff-f',
    secretaryId: 'staff-g',
    reshoot: false,
    engagementRate: 5.4,
    publishedAt: daysAgo(18),
  },
  {
    id: 'shoot-3',
    propertyId: 'prop-4',
    title: 'Banana Island mansion — flagship film',
    location: 'Ikoyi, Lagos',
    stage: 'EDITING',
    scheduledFor: daysAgo(5),
    prepCompleteAt: daysAgo(7),
    presenterId: 'staff-f',
    secretaryId: 'staff-g',
    reshoot: false,
    engagementRate: null,
    publishedAt: null,
  },
  {
    id: 'shoot-4',
    propertyId: 'prop-11',
    title: 'Cedarwood 5-bed detached',
    location: 'Lekki Phase 1, Lagos',
    stage: 'FILMED',
    scheduledFor: daysAgo(2),
    prepCompleteAt: daysAgo(4),
    presenterId: 'staff-f',
    secretaryId: 'staff-g',
    reshoot: false,
    engagementRate: null,
    publishedAt: null,
  },
  {
    id: 'shoot-5',
    propertyId: 'prop-15',
    title: 'Ikoyi shortlet — 60 second reel',
    location: 'Ikoyi, Lagos',
    stage: 'SCHEDULED',
    scheduledFor: daysAhead(2),
    prepCompleteAt: null,
    presenterId: 'staff-f',
    secretaryId: 'staff-g',
    reshoot: false,
    engagementRate: null,
    publishedAt: null,
  },
  {
    id: 'shoot-6',
    propertyId: 'prop-3',
    title: 'Alaro Court 2-bed apartment',
    location: 'Ajah, Lagos',
    stage: 'REQUESTED',
    scheduledFor: null,
    prepCompleteAt: null,
    presenterId: 'staff-f',
    secretaryId: 'staff-g',
    reshoot: false,
    engagementRate: null,
    publishedAt: null,
  },
  {
    id: 'shoot-7',
    propertyId: null,
    title: 'PropertyLoop escrow explainer',
    location: 'Lekki Swiss Mall office',
    stage: 'PREPPED',
    scheduledFor: daysAhead(1),
    prepCompleteAt: hoursAgo(6),
    presenterId: 'staff-f',
    secretaryId: 'staff-g',
    reshoot: false,
    engagementRate: null,
    publishedAt: null,
  },
  {
    id: 'shoot-8',
    propertyId: 'prop-7',
    title: 'Lekki shortlet reel',
    location: 'Lekki, Lagos',
    stage: 'PUBLISHED',
    scheduledFor: daysAgo(28),
    prepCompleteAt: daysAgo(30),
    presenterId: 'staff-f',
    secretaryId: 'staff-g',
    reshoot: true,
    engagementRate: 3.1,
    publishedAt: daysAgo(24),
  },
  {
    id: 'shoot-9',
    propertyId: 'prop-18',
    title: 'Osogbo GRA duplex — Osun chapter launch',
    location: 'Osogbo, Osun',
    stage: 'SCHEDULED',
    scheduledFor: daysAhead(5),
    prepCompleteAt: null,
    presenterId: 'staff-f',
    secretaryId: 'staff-g',
    reshoot: false,
    engagementRate: null,
    publishedAt: null,
  },
  {
    id: 'shoot-10',
    propertyId: 'prop-6',
    title: 'VI serviced apartment tour',
    location: 'Victoria Island, Lagos',
    stage: 'PUBLISHED',
    scheduledFor: daysAgo(9),
    prepCompleteAt: daysAgo(11),
    presenterId: 'staff-f',
    secretaryId: 'staff-g',
    reshoot: false,
    engagementRate: 5.9,
    publishedAt: daysAgo(6),
  },
  {
    id: 'shoot-11',
    propertyId: 'prop-13',
    title: 'Greenfield Phase 3 — sold walkthrough',
    location: 'Ikate, Lagos',
    stage: 'PUBLISHED',
    scheduledFor: daysAgo(35),
    prepCompleteAt: daysAgo(37),
    presenterId: 'staff-f',
    secretaryId: 'staff-g',
    reshoot: false,
    engagementRate: 7.1,
    publishedAt: daysAgo(31),
  },
  {
    id: 'shoot-12',
    propertyId: 'prop-16',
    title: 'Lekki County mansion — pending photos',
    location: 'Lekki, Lagos',
    stage: 'REQUESTED',
    scheduledFor: null,
    prepCompleteAt: null,
    presenterId: 'staff-f',
    secretaryId: 'staff-g',
    reshoot: false,
    engagementRate: null,
    publishedAt: null,
  },
]

/* ─── Content ────────────────────────────────────────────────────────── */

export const CONTENT: ContentPiece[] = [
  {
    id: 'content-1',
    title: 'Cedarwood Phase 2 launch carousel',
    channel: 'INSTAGRAM',
    kind: 'CAROUSEL',
    publishedAt: daysAgo(10),
    scheduledFor: null,
    engagementRate: 5.8,
    leadsGenerated: 14,
    ownerId: 'staff-d',
  },
  {
    id: 'content-2',
    title: '5 things to check before buying off-plan',
    channel: 'LINKEDIN',
    kind: 'POST',
    publishedAt: daysAgo(7),
    scheduledFor: null,
    engagementRate: 4.2,
    leadsGenerated: 6,
    ownerId: 'staff-d',
  },
  {
    id: 'content-3',
    title: 'Greenfield tour — reel cut',
    channel: 'INSTAGRAM',
    kind: 'VIDEO',
    publishedAt: daysAgo(17),
    scheduledFor: null,
    engagementRate: 6.4,
    leadsGenerated: 22,
    ownerId: 'staff-d',
  },
  {
    id: 'content-4',
    title: 'Weekly new listings digest',
    channel: 'WHATSAPP',
    kind: 'POST',
    publishedAt: daysAgo(3),
    scheduledFor: null,
    engagementRate: 8.9,
    leadsGenerated: 31,
    ownerId: 'staff-d',
  },
  {
    id: 'content-5',
    title: 'Osun chapter announcement',
    channel: 'WHATSAPP',
    kind: 'POST',
    publishedAt: daysAgo(12),
    scheduledFor: null,
    engagementRate: 7.2,
    leadsGenerated: 9,
    ownerId: 'staff-d',
  },
  {
    id: 'content-6',
    title: 'Q4 buyer campaign — paid',
    channel: 'INSTAGRAM',
    kind: 'CAMPAIGN',
    publishedAt: daysAgo(20),
    scheduledFor: null,
    engagementRate: 3.6,
    leadsGenerated: 48,
    ownerId: 'staff-d',
  },
  {
    id: 'content-7',
    title: 'How PropertyLoop escrow protects you',
    channel: 'LINKEDIN',
    kind: 'GRAPHIC',
    publishedAt: null,
    scheduledFor: daysAhead(2),
    engagementRate: null,
    leadsGenerated: 0,
    ownerId: 'staff-d',
  },
  {
    id: 'content-8',
    title: 'Banana Island flagship teaser',
    channel: 'TIKTOK',
    kind: 'VIDEO',
    publishedAt: null,
    scheduledFor: daysAhead(4),
    engagementRate: null,
    leadsGenerated: 0,
    ownerId: 'staff-d',
  },
  {
    id: 'content-9',
    title: 'Lagos rent price index — September',
    channel: 'LINKEDIN',
    kind: 'CAROUSEL',
    publishedAt: daysAgo(1),
    scheduledFor: null,
    engagementRate: 4.9,
    leadsGenerated: 4,
    ownerId: 'staff-d',
  },
  {
    id: 'content-10',
    title: 'Agent recruitment drive',
    channel: 'X',
    kind: 'POST',
    publishedAt: daysAgo(5),
    scheduledFor: null,
    engagementRate: 2.1,
    leadsGenerated: 3,
    ownerId: 'staff-d',
  },
]

/* ─── Operations queue ───────────────────────────────────────────────── */

export const OPS: OpsItem[] = [
  {
    id: 'ops-1',
    kind: 'WITHDRAWAL',
    subject: 'Vendor payout — Adebayo Plumbing',
    amountNaira: 185_000,
    openedAt: daysAgo(4),
    assigneeId: null,
    resolved: false,
    urgent: true,
  },
  {
    id: 'ops-2',
    kind: 'WITHDRAWAL',
    subject: 'Vendor payout — Bright Electricals',
    amountNaira: 92_500,
    openedAt: daysAgo(2),
    assigneeId: null,
    resolved: false,
    urgent: false,
  },
  {
    id: 'ops-3',
    kind: 'KYC',
    subject: 'Agent verification — Beacon Realty (3 agents)',
    amountNaira: null,
    openedAt: daysAgo(3),
    assigneeId: 'staff-e-ngozi',
    resolved: false,
    urgent: false,
  },
  {
    id: 'ops-4',
    kind: 'KYC',
    subject: 'Vendor verification — Marble & Stone',
    amountNaira: null,
    openedAt: daysAgo(6),
    assigneeId: null,
    resolved: false,
    urgent: true,
  },
  {
    id: 'ops-5',
    kind: 'DISPUTE',
    subject: 'Escrow dispute — job #4471 painting',
    amountNaira: 240_000,
    openedAt: daysAgo(5),
    assigneeId: 'staff-b',
    resolved: false,
    urgent: true,
  },
  {
    id: 'ops-6',
    kind: 'REPORT',
    subject: 'Reported listing — suspected duplicate',
    amountNaira: null,
    openedAt: daysAgo(1),
    assigneeId: 'staff-c-ola',
    resolved: false,
    urgent: false,
  },
  {
    id: 'ops-7',
    kind: 'REPORT',
    subject: 'Feed post reported — spam',
    amountNaira: null,
    openedAt: hoursAgo(9),
    assigneeId: null,
    resolved: false,
    urgent: false,
  },
  {
    id: 'ops-8',
    kind: 'LISTING_REVIEW',
    subject: 'Lekki County mansion — no photos, no documents',
    amountNaira: null,
    openedAt: hoursAgo(20),
    assigneeId: 'staff-c-sodiq1',
    resolved: false,
    urgent: false,
  },
  {
    id: 'ops-9',
    kind: 'ENQUIRY',
    subject: 'Unanswered enquiry — Grace Okon',
    amountNaira: null,
    openedAt: hoursAgo(3),
    assigneeId: 'staff-e-ngozi',
    resolved: false,
    urgent: true,
  },
  {
    id: 'ops-10',
    kind: 'ENQUIRY',
    subject: 'Unanswered enquiry — Ibrahim Yakubu',
    amountNaira: null,
    openedAt: hoursAgo(1),
    assigneeId: 'staff-e-ngozi',
    resolved: false,
    urgent: false,
  },
  {
    id: 'ops-11',
    kind: 'KYC',
    subject: 'Agent verification — Ile-Ife Property Partners',
    amountNaira: null,
    openedAt: daysAgo(8),
    assigneeId: null,
    resolved: true,
    urgent: false,
  },
  {
    id: 'ops-12',
    kind: 'WITHDRAWAL',
    subject: 'Vendor payout — Kunle Carpentry',
    amountNaira: 310_000,
    openedAt: daysAgo(11),
    assigneeId: 'staff-a',
    resolved: true,
    urgent: false,
  },
  {
    id: 'ops-13',
    kind: 'LISTING_REVIEW',
    subject: 'Osun Grove Block B — 1 of 4 documents',
    amountNaira: null,
    openedAt: daysAgo(1),
    assigneeId: 'staff-sodiq2',
    resolved: false,
    urgent: false,
  },
  {
    id: 'ops-14',
    kind: 'REPORT',
    subject: 'User reported — abusive messages',
    amountNaira: null,
    openedAt: daysAgo(2),
    assigneeId: null,
    resolved: false,
    urgent: true,
  },
]

/* ─── Threads ────────────────────────────────────────────────────────── */

export const THREADS: Thread[] = [
  {
    id: 'thread-1',
    title: 'Crestview — missing C of O before we can publish',
    subject: { kind: 'PROPERTY', id: 'prop-8' },
    participantIds: ['staff-c-sodiq1', 'staff-c-ola', 'staff-b'],
    resolved: false,
    createdAt: daysAgo(2),
    messages: [
      {
        id: 'tm-1',
        authorId: 'staff-c-sodiq1',
        text: 'Crestview sent 3 photos and a survey plan only. No C of O. Do we hold or publish as unverified?',
        createdAt: daysAgo(2),
      },
      {
        id: 'tm-2',
        authorId: 'staff-c-ola',
        text: 'Hold. We agreed nothing goes live without C of O or a written explanation from the developer.',
        createdAt: daysAgo(2, 14),
      },
      {
        id: 'tm-3',
        authorId: 'staff-b',
        text: 'Agreed — hold. I will raise it with Ngozi Uche on our call tomorrow. Do not publish.',
        createdAt: hoursAgo(30),
      },
    ],
  },
  {
    id: 'thread-2',
    title: 'Alaro Court — push for exclusive before Thursday',
    subject: { kind: 'DEAL', id: 'deal-2' },
    participantIds: ['staff-b', 'staff-a'],
    resolved: false,
    createdAt: daysAgo(4),
    messages: [
      {
        id: 'tm-4',
        authorId: 'staff-b',
        text: 'Alaro have given us inventory on 16 units but no mandate. A competitor is meeting them Thursday.',
        createdAt: daysAgo(4),
      },
      {
        id: 'tm-5',
        authorId: 'staff-a',
        text: 'Offer the co-branded launch campaign as the sweetener, but only against an exclusive. Not primary.',
        createdAt: daysAgo(3),
      },
      {
        id: 'tm-6',
        authorId: 'staff-b',
        text: 'Understood. Meeting them Wednesday morning to get ahead of it.',
        createdAt: daysAgo(1),
      },
    ],
  },
  {
    id: 'thread-3',
    title: 'Banana Island film — edit running long',
    subject: { kind: 'SHOOT', id: 'shoot-3' },
    participantIds: ['staff-f', 'staff-g', 'staff-d'],
    resolved: false,
    createdAt: daysAgo(3),
    messages: [
      {
        id: 'tm-7',
        authorId: 'staff-g',
        text: 'Footage is all in. Edit is at 4 minutes — too long for a reel cut.',
        createdAt: daysAgo(3),
      },
      {
        id: 'tm-8',
        authorId: 'staff-d',
        text: 'Give me a 60s vertical for Instagram and TikTok, keep the 4 min as the flagship for the listing page.',
        createdAt: daysAgo(2),
      },
      {
        id: 'tm-9',
        authorId: 'staff-f',
        text: 'Works. I will record a shorter voiceover for the 60s version tomorrow.',
        createdAt: hoursAgo(20),
      },
    ],
  },
  {
    id: 'thread-4',
    title: 'What counts as a qualified lead?',
    subject: { kind: 'GENERAL', id: null },
    participantIds: ['staff-b', 'staff-d', 'staff-e-ngozi', 'staff-a'],
    resolved: true,
    createdAt: daysAgo(9),
    messages: [
      {
        id: 'tm-10',
        authorId: 'staff-d',
        text: 'We are counting differently. Marketing counts an enquiry with contact details. The GM only counts ones with a budget.',
        createdAt: daysAgo(9),
      },
      {
        id: 'tm-11',
        authorId: 'staff-b',
        text: 'If we count every enquiry, 150 leads a month at 25% conversion means 37 closed deals. That is not real.',
        createdAt: daysAgo(9, 15),
      },
      {
        id: 'tm-12',
        authorId: 'staff-a',
        text: 'Settle it now: qualified = budget confirmed, timeline stated, and a specific property or service named. All three. Anything else is an enquiry.',
        createdAt: daysAgo(8),
      },
      {
        id: 'tm-13',
        authorId: 'staff-e-ngozi',
        text: 'Noted. I will apply that when I triage the inbox, so the flag is set once and we all read the same number.',
        createdAt: daysAgo(8, 16),
      },
    ],
  },
  {
    id: 'thread-5',
    title: 'Musa Danjuma — ₦900m offer on Banana Island',
    subject: { kind: 'LEAD', id: 'lead-15' },
    participantIds: ['staff-a', 'staff-b'],
    resolved: false,
    createdAt: daysAgo(5),
    messages: [
      {
        id: 'tm-14',
        authorId: 'staff-a',
        text: 'Second viewing went well. He is at ₦900m against ₦950m asking. I am handling this one directly.',
        createdAt: daysAgo(5),
      },
      {
        id: 'tm-15',
        authorId: 'staff-b',
        text: 'Noted — leaving it with you. Flag it if you want me to prepare the paperwork.',
        createdAt: daysAgo(3),
      },
    ],
  },
  {
    id: 'thread-6',
    title: 'Osun chapter — first 6 listings',
    subject: { kind: 'GENERAL', id: null },
    participantIds: ['staff-sodiq2', 'staff-c-sodiq1', 'staff-b', 'staff-d'],
    resolved: false,
    createdAt: daysAgo(6),
    messages: [
      {
        id: 'tm-16',
        authorId: 'staff-sodiq2',
        text: 'Osun Grove have given us 14 units. Two are photographed, the rest need a trip to Osogbo.',
        createdAt: daysAgo(6),
      },
      {
        id: 'tm-17',
        authorId: 'staff-c-sodiq1',
        text: 'I can come down Thursday and Friday. We should shoot all remaining units in one trip.',
        createdAt: daysAgo(5),
      },
      {
        id: 'tm-18',
        authorId: 'staff-d',
        text: 'If the Ambassador travels with you we can get the Osun launch video in the same trip. Cheaper than two journeys.',
        createdAt: daysAgo(4),
      },
      {
        id: 'tm-19',
        authorId: 'staff-b',
        text: 'Approved. Coordinate dates with the Secretary so it lands before month end.',
        createdAt: daysAgo(2),
      },
    ],
  },
]

/* ─── Targets ────────────────────────────────────────────────────────── */
// Ranges are taken from the September 2026 org document. `provenance` marks
// whether the actual is queryable or typed in by a person.

export const TARGETS: Target[] = [
  // Staff A — MD / CEO
  {
    id: 't-a1',
    staffId: 'staff-a',
    label: 'High-value partnerships / exclusive mandates',
    min: 2,
    max: 2,
    actual: 1,
    unit: 'COUNT',
    provenance: 'DATABASE',
  },
  {
    id: 't-a2',
    staffId: 'staff-a',
    label: 'Total company revenue',
    min: 15_000_000,
    max: 25_000_000,
    actual: 9_400_000,
    unit: 'NAIRA',
    provenance: 'DATABASE',
  },
  {
    id: 't-a3',
    staffId: 'staff-a',
    label: 'Strategic high-ticket deals closed',
    min: 1,
    max: 1,
    actual: 0,
    unit: 'COUNT',
    provenance: 'DATABASE',
  },

  // Staff B — General Manager
  {
    id: 't-b1',
    staffId: 'staff-b',
    label: 'New property mandates',
    min: 8,
    max: 12,
    actual: 5,
    unit: 'COUNT',
    provenance: 'DATABASE',
  },
  {
    id: 't-b2',
    staffId: 'staff-b',
    label: 'Exclusive mandates',
    min: 3,
    max: 3,
    actual: 2,
    unit: 'COUNT',
    provenance: 'DATABASE',
  },
  {
    id: 't-b3',
    staffId: 'staff-b',
    label: 'Direct sales / commission revenue',
    min: 8_000_000,
    max: 12_000_000,
    actual: 6_100_000,
    unit: 'NAIRA',
    provenance: 'DATABASE',
  },
  {
    id: 't-b4',
    staffId: 'staff-b',
    label: 'Qualified lead conversion',
    min: 25,
    max: 25,
    actual: 18,
    unit: 'PERCENT',
    provenance: 'DATABASE',
  },
  {
    id: 't-b5',
    staffId: 'staff-b',
    label: 'Realtors / agents onboarded',
    min: 10,
    max: 10,
    actual: 6,
    unit: 'COUNT',
    provenance: 'DATABASE',
  },
  {
    id: 't-b6',
    staffId: 'staff-b',
    label: 'Advertising packages sold',
    min: 5,
    max: 5,
    actual: 2,
    unit: 'COUNT',
    provenance: 'DATABASE',
  },

  // Staff C — Property & Listing (Ola)
  {
    id: 't-c1',
    staffId: 'staff-c-ola',
    label: 'Verified properties listed',
    min: 20,
    max: 30,
    actual: 14,
    unit: 'COUNT',
    provenance: 'DATABASE',
  },
  {
    id: 't-c2',
    staffId: 'staff-c-ola',
    label: 'New developers / owners onboarded',
    min: 4,
    max: 5,
    actual: 3,
    unit: 'COUNT',
    provenance: 'DATABASE',
  },
  {
    id: 't-c3',
    staffId: 'staff-c-ola',
    label: 'Listings with complete documents',
    min: 100,
    max: 100,
    actual: 82,
    unit: 'PERCENT',
    provenance: 'DATABASE',
  },

  // Staff C — Property & Listing (Sodiq 1st)
  {
    id: 't-c4',
    staffId: 'staff-c-sodiq1',
    label: 'Verified properties listed',
    min: 20,
    max: 30,
    actual: 9,
    unit: 'COUNT',
    provenance: 'DATABASE',
  },
  {
    id: 't-c5',
    staffId: 'staff-c-sodiq1',
    label: 'New developers / owners onboarded',
    min: 4,
    max: 5,
    actual: 2,
    unit: 'COUNT',
    provenance: 'DATABASE',
  },
  {
    id: 't-c6',
    staffId: 'staff-c-sodiq1',
    label: 'Listings with complete documents',
    min: 100,
    max: 100,
    actual: 61,
    unit: 'PERCENT',
    provenance: 'DATABASE',
  },

  // Staff D — Marketing
  {
    id: 't-d1',
    staffId: 'staff-d',
    label: 'Qualified leads generated',
    min: 150,
    max: 200,
    actual: 96,
    unit: 'COUNT',
    provenance: 'DATABASE',
  },
  {
    id: 't-d2',
    staffId: 'staff-d',
    label: 'Content pieces published',
    min: 20,
    max: 20,
    actual: 8,
    unit: 'COUNT',
    provenance: 'DATABASE',
  },
  {
    id: 't-d3',
    staffId: 'staff-d',
    label: 'Average engagement rate',
    min: 4,
    max: 4,
    actual: 5.1,
    unit: 'PERCENT',
    provenance: 'MANUAL',
  },
  {
    id: 't-d4',
    staffId: 'staff-d',
    label: 'Structured campaigns run',
    min: 2,
    max: 2,
    actual: 1,
    unit: 'COUNT',
    provenance: 'DATABASE',
  },
  {
    id: 't-d5',
    staffId: 'staff-d',
    label: 'Channel following growth',
    min: 15,
    max: 20,
    actual: 11,
    unit: 'PERCENT',
    provenance: 'MANUAL',
  },

  // Staff E — Operations (Ngozi)
  {
    id: 't-e1',
    staffId: 'staff-e-ngozi',
    label: 'Enquiries answered within 30 min',
    min: 100,
    max: 100,
    actual: 74,
    unit: 'PERCENT',
    provenance: 'DATABASE',
  },
  {
    id: 't-e2',
    staffId: 'staff-e-ngozi',
    label: 'Customer satisfaction',
    min: 90,
    max: 90,
    actual: 92,
    unit: 'PERCENT',
    provenance: 'MANUAL',
  },
  {
    id: 't-e3',
    staffId: 'staff-e-ngozi',
    label: 'Complaints resolved in 24–48h',
    min: 95,
    max: 95,
    actual: 88,
    unit: 'PERCENT',
    provenance: 'DATABASE',
  },
  {
    id: 't-e4',
    staffId: 'staff-e-ngozi',
    label: 'Realtors onboarded within 48h',
    min: 100,
    max: 100,
    actual: 100,
    unit: 'PERCENT',
    provenance: 'DATABASE',
  },

  // Staff F — Ambassador
  {
    id: 't-f1',
    staffId: 'staff-f',
    label: 'Property presentation videos delivered',
    min: 25,
    max: 30,
    actual: 11,
    unit: 'COUNT',
    provenance: 'DATABASE',
  },
  {
    id: 't-f2',
    staffId: 'staff-f',
    label: 'Average video engagement',
    min: 5,
    max: 5,
    actual: 5.7,
    unit: 'PERCENT',
    provenance: 'MANUAL',
  },
  {
    id: 't-f3',
    staffId: 'staff-f',
    label: 'Campaign videos',
    min: 4,
    max: 4,
    actual: 2,
    unit: 'COUNT',
    provenance: 'DATABASE',
  },
  {
    id: 't-f4',
    staffId: 'staff-f',
    label: 'Reshoot rate (lower is better)',
    min: 10,
    max: 10,
    actual: 8,
    unit: 'PERCENT',
    ceiling: true,
    provenance: 'DATABASE',
  },

  // Staff G — Secretary
  {
    id: 't-g1',
    staffId: 'staff-g',
    label: 'Shoots prepped 24h in advance',
    min: 100,
    max: 100,
    actual: 91,
    unit: 'PERCENT',
    provenance: 'DATABASE',
  },
  {
    id: 't-g2',
    staffId: 'staff-g',
    label: 'Filming schedule conflicts',
    min: 0,
    max: 0,
    actual: 1,
    unit: 'COUNT',
    ceiling: true,
    provenance: 'MANUAL',
  },
  {
    id: 't-g3',
    staffId: 'staff-g',
    label: 'Administrative task accuracy',
    min: 98,
    max: 98,
    actual: 97,
    unit: 'PERCENT',
    provenance: 'MANUAL',
  },

  // Osun chapter — Sodiq (2nd)
  {
    id: 't-o1',
    staffId: 'staff-sodiq2',
    label: 'Osun properties listed',
    min: 10,
    max: 15,
    actual: 4,
    unit: 'COUNT',
    provenance: 'DATABASE',
  },
  {
    id: 't-o2',
    staffId: 'staff-sodiq2',
    label: 'Osun developer partnerships',
    min: 2,
    max: 3,
    actual: 2,
    unit: 'COUNT',
    provenance: 'DATABASE',
  },
  {
    id: 't-o3',
    staffId: 'staff-sodiq2',
    label: 'Osun qualified leads',
    min: 20,
    max: 30,
    actual: 7,
    unit: 'COUNT',
    provenance: 'DATABASE',
  },
]
